spring:
  application:
    name: umc3_teamproject
  datasource:
    url: jdbc:mysql://localhost:3306/textroad?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Ff2052767!

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

springdoc:
  swagger-ui:
    path: docs
  show-actuator: true